---
- name: Verify default scenario
  hosts: platforms
  tasks:
    - name: Include get authorized_keys
      include: ../resources/playbooks/verify/get_authorized_keys.yml
    - name: Include assert authorized_keys
      include: ../resources/playbooks/verify/assert_authorized_keys_empty.yml
